"""Test and build GitHub Pages' main/docs source without workflow OAuth scope."""

import shutil
import subprocess
import sys
from pathlib import Path

import build_site


HERE = Path(__file__).resolve().parent
DOCS = HERE.parent / "docs"
MARKER = DOCS / ".rl-learning-generated"


def main():
    subprocess.run(["npm", "ci"], cwd=HERE, check=True)
    subprocess.run(["npm", "run", "build:editor"], cwd=HERE, check=True)
    for script in ("app.js", "worker.js"):
        subprocess.run(["node", "--check", script], cwd=HERE, check=True)
    subprocess.run(
        [sys.executable, "-m", "unittest", "-q",
         "test_server.py", "test_site_build.py", "test_mdp.py",
         "test_browser_multichapter.py", "test_browser_mdp.py"],
        cwd=HERE, check=True,
    )

    if DOCS.exists() and (DOCS.is_symlink() or not MARKER.is_file()):
        raise RuntimeError("docs/ 已存在且不是本站构建目录；拒绝覆盖")
    DOCS.mkdir(parents=True, exist_ok=True)
    output = DOCS / "checkpoint"
    if output.exists():
        if output.is_symlink() or not output.is_dir():
            raise RuntimeError("docs/checkpoint 不是普通目录；拒绝覆盖")
        shutil.rmtree(output)
    build_site.build(output)
    (DOCS / "index.html").write_text(
        '<!doctype html><html lang="zh-CN"><meta charset="utf-8">'
        '<meta http-equiv="refresh" content="0;url=./checkpoint/">'
        '<title>RL Learning Lab</title><a href="./checkpoint/">进入学习站</a></html>\n',
        encoding="utf-8",
    )
    (DOCS / ".nojekyll").touch()
    MARKER.write_text("Generated by checkpoint/publish_pages.py; do not edit by hand.\n",
                      encoding="utf-8")
    print("GitHub Pages source ready in", DOCS)


if __name__ == "__main__":
    main()
