"""Test and build GitHub Pages' main/docs source without workflow OAuth scope."""

import shutil
import subprocess
import sys
import os
from pathlib import Path

import build_site


HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent
HUB_DIR = REPO_ROOT / "hub"
if str(HUB_DIR) not in sys.path:
    sys.path.insert(0, str(HUB_DIR))

import build_catalog  # noqa: E402  (needs hub on sys.path)


DOCS = REPO_ROOT / "docs"
MARKER_NAME = ".rl-learning-generated"
MARKER = DOCS / MARKER_NAME

REDIRECT_HTML = (
    '<!doctype html><html lang="zh-CN"><meta charset="utf-8">'
    '<meta http-equiv="refresh" content="0;url=./hub/">'
    '<title>RL Learning Lab</title><a href="./hub/">进入学习站</a></html>\n'
)


def build_pages(docs=DOCS, repo_root=None):
    """Safely rebuild the static Pages source: checkpoint + hub + root redirect.

    Caller (``main``) runs the npm/node/unittest validations first. This helper
    performs only the static file rebuild and refuses to overwrite a ``docs``
    directory that is not a generated site. It also accepts ``repo_root`` so
    tests can point the hub build at a temporary repository fixture.
    """
    root = Path(repo_root).resolve() if repo_root is not None else REPO_ROOT
    # Validate the *lexical* (unresolved) path first: a symlinked docs/ must be
    # rejected even when it points at an already-marked generated folder.
    raw = Path(os.path.abspath(Path(docs).expanduser()))
    if raw.is_symlink():
        raise RuntimeError("docs/ 是符号链接；拒绝覆盖")
    if raw.exists() and not raw.is_dir():
        raise RuntimeError("docs/ 既非目录也非本站构建目录；拒绝覆盖")
    lex_repo = Path(os.path.abspath(root))
    for ancestor in raw.parents:
        if ancestor == ancestor.parent:
            break
        if ancestor.is_symlink() and (
                ancestor == lex_repo or lex_repo in ancestor.parents
                or ancestor in lex_repo.parents):
            raise RuntimeError("docs/ 路径含符号链接组件: %s" % ancestor)

    docs = raw.resolve()
    marker = docs / MARKER_NAME
    targets = {
        "marker": marker,
        "index.html": docs / "index.html",
        ".nojekyll": docs / ".nojekyll",
        "checkpoint": docs / "checkpoint",
        "hub": docs / "hub",
    }
    for name, target in targets.items():
        if target.is_symlink():
            raise RuntimeError("docs/%s 是符号链接；拒绝覆盖" % name)
    if docs.exists() and not marker.is_file():
        raise RuntimeError("docs/ 已存在且不是本站构建目录；拒绝覆盖")
    docs.mkdir(parents=True, exist_ok=True)
    for name in ("checkpoint", "hub"):
        target = targets[name]
        if target.exists():
            if not target.is_dir():
                raise RuntimeError("docs/%s 不是普通目录；拒绝覆盖" % name)
            shutil.rmtree(target)
    build_site.build(targets["checkpoint"])
    build_catalog.build_hub(targets["hub"], repo_root=root)

    targets["index.html"].write_text(REDIRECT_HTML, encoding="utf-8")
    targets[".nojekyll"].touch()
    marker.write_text("Generated by checkpoint/publish_pages.py; do not edit by hand.\n",
                      encoding="utf-8")
    print("GitHub Pages source ready in", docs)
    return docs


def main():
    subprocess.run(["npm", "ci"], cwd=HERE, check=True)
    subprocess.run(["npm", "run", "build:editor"], cwd=HERE, check=True)
    for script in ("app.js", "worker.js"):
        subprocess.run(["node", "--check", script], cwd=HERE, check=True)
    subprocess.run(
        [sys.executable, "-m", "unittest", "-q",
         "test_server.py", "test_site_build.py", "test_mdp.py",
         "test_hub_catalog.py", "test_browser_multichapter.py", "test_browser_mdp.py"],
        cwd=HERE, check=True,
    )

    build_pages()


if __name__ == "__main__":
    main()
